# config.yaml (환경마다 달라질 수 있지만 기본값)
kakao:
  domain: "https://kauth.kakao.com"
  redirectURI: "http://localhost:8080/oauth/callback"
  apiHost: "https://kapi.kakao.com"
  
google:
  domain: "https://kauth.kakao.com"
  redirectURI: "http://localhost:8080/oauth/callback"
  apiHost: "https://kapi.kakao.com"

google_smtp:
  smtpHost: "smtp.gmail.com"
  smtpPort: "587"

db:
  host: "127.0.0.1"
  port: "3306"
  database: "itpl_db"

rdb:
  database: 0

grpc:
  host: "localhost"
  update_port : "50052"
  recommend_port : "50051"