# config.yaml (환경마다 달라질 수 있지만 기본값)
kakao:
  domain: "https://kauth.kakao.com"
  redirectURI: "/oauth/callback"
  apiHost: "https://kapi.kakao.com"

db:
  host: "localhost"
  port: "3306"
  database: "itpl_db"
  
