// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: recommender.proto

package recommend_client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Genres        []int32                `protobuf:"varint,2,rep,packed,name=genres,proto3" json:"genres,omitempty"`
	Artists       []string               `protobuf:"bytes,3,rep,name=artists,proto3" json:"artists,omitempty"`
	FavIds        []string               `protobuf:"bytes,4,rep,name=fav_ids,json=favIds,proto3" json:"fav_ids,omitempty"`
	Topk          int32                  `protobuf:"varint,5,opt,name=topk,proto3" json:"topk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_recommender_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommender_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_recommender_proto_rawDescGZIP(), []int{0}
}

func (x *UserRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserRequest) GetGenres() []int32 {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *UserRequest) GetArtists() []string {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *UserRequest) GetFavIds() []string {
	if x != nil {
		return x.FavIds
	}
	return nil
}

func (x *UserRequest) GetTopk() int32 {
	if x != nil {
		return x.Topk
	}
	return 0
}

type Concert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Concert) Reset() {
	*x = Concert{}
	mi := &file_recommender_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Concert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Concert) ProtoMessage() {}

func (x *Concert) ProtoReflect() protoreflect.Message {
	mi := &file_recommender_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Concert.ProtoReflect.Descriptor instead.
func (*Concert) Descriptor() ([]byte, []int) {
	return file_recommender_proto_rawDescGZIP(), []int{1}
}

func (x *Concert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Concert) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Concert) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type RecommendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Concerts      []*Concert             `protobuf:"bytes,1,rep,name=concerts,proto3" json:"concerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendResponse) Reset() {
	*x = RecommendResponse{}
	mi := &file_recommender_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResponse) ProtoMessage() {}

func (x *RecommendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommender_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResponse.ProtoReflect.Descriptor instead.
func (*RecommendResponse) Descriptor() ([]byte, []int) {
	return file_recommender_proto_rawDescGZIP(), []int{2}
}

func (x *RecommendResponse) GetConcerts() []*Concert {
	if x != nil {
		return x.Concerts
	}
	return nil
}

var File_recommender_proto protoreflect.FileDescriptor

const file_recommender_proto_rawDesc = "" +
	"\n" +
	"\x11recommender.proto\"\x85\x01\n" +
	"\vUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06genres\x18\x02 \x03(\x05R\x06genres\x12\x18\n" +
	"\aartists\x18\x03 \x03(\tR\aartists\x12\x17\n" +
	"\afav_ids\x18\x04 \x03(\tR\x06favIds\x12\x12\n" +
	"\x04topk\x18\x05 \x01(\x05R\x04topk\"C\n" +
	"\aConcert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\"9\n" +
	"\x11RecommendResponse\x12$\n" +
	"\bconcerts\x18\x01 \x03(\v2\b.ConcertR\bconcerts2<\n" +
	"\vRecommender\x12-\n" +
	"\tRecommend\x12\f.UserRequest\x1a\x12.RecommendResponseB*Z(ITPL-server/grpc_client/recommend_clientb\x06proto3"

var (
	file_recommender_proto_rawDescOnce sync.Once
	file_recommender_proto_rawDescData []byte
)

func file_recommender_proto_rawDescGZIP() []byte {
	file_recommender_proto_rawDescOnce.Do(func() {
		file_recommender_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recommender_proto_rawDesc), len(file_recommender_proto_rawDesc)))
	})
	return file_recommender_proto_rawDescData
}

var file_recommender_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_recommender_proto_goTypes = []any{
	(*UserRequest)(nil),       // 0: UserRequest
	(*Concert)(nil),           // 1: Concert
	(*RecommendResponse)(nil), // 2: RecommendResponse
}
var file_recommender_proto_depIdxs = []int32{
	1, // 0: RecommendResponse.concerts:type_name -> Concert
	0, // 1: Recommender.Recommend:input_type -> UserRequest
	2, // 2: Recommender.Recommend:output_type -> RecommendResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_recommender_proto_init() }
func file_recommender_proto_init() {
	if File_recommender_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recommender_proto_rawDesc), len(file_recommender_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recommender_proto_goTypes,
		DependencyIndexes: file_recommender_proto_depIdxs,
		MessageInfos:      file_recommender_proto_msgTypes,
	}.Build()
	File_recommender_proto = out.File
	file_recommender_proto_goTypes = nil
	file_recommender_proto_depIdxs = nil
}
