// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: update.proto

package update_client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConcertUpdater_UpdateConcerts_FullMethodName = "/ConcertUpdater/UpdateConcerts"
)

// ConcertUpdaterClient is the client API for ConcertUpdater service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConcertUpdaterClient interface {
	UpdateConcerts(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type concertUpdaterClient struct {
	cc grpc.ClientConnInterface
}

func NewConcertUpdaterClient(cc grpc.ClientConnInterface) ConcertUpdaterClient {
	return &concertUpdaterClient{cc}
}

func (c *concertUpdaterClient) UpdateConcerts(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, ConcertUpdater_UpdateConcerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConcertUpdaterServer is the server API for ConcertUpdater service.
// All implementations must embed UnimplementedConcertUpdaterServer
// for forward compatibility.
type ConcertUpdaterServer interface {
	UpdateConcerts(context.Context, *UpdateRequest) (*UpdateResponse, error)
	mustEmbedUnimplementedConcertUpdaterServer()
}

// UnimplementedConcertUpdaterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConcertUpdaterServer struct{}

func (UnimplementedConcertUpdaterServer) UpdateConcerts(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConcerts not implemented")
}
func (UnimplementedConcertUpdaterServer) mustEmbedUnimplementedConcertUpdaterServer() {}
func (UnimplementedConcertUpdaterServer) testEmbeddedByValue()                        {}

// UnsafeConcertUpdaterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConcertUpdaterServer will
// result in compilation errors.
type UnsafeConcertUpdaterServer interface {
	mustEmbedUnimplementedConcertUpdaterServer()
}

func RegisterConcertUpdaterServer(s grpc.ServiceRegistrar, srv ConcertUpdaterServer) {
	// If the following call pancis, it indicates UnimplementedConcertUpdaterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConcertUpdater_ServiceDesc, srv)
}

func _ConcertUpdater_UpdateConcerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConcertUpdaterServer).UpdateConcerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConcertUpdater_UpdateConcerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConcertUpdaterServer).UpdateConcerts(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConcertUpdater_ServiceDesc is the grpc.ServiceDesc for ConcertUpdater service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConcertUpdater_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ConcertUpdater",
	HandlerType: (*ConcertUpdaterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateConcerts",
			Handler:    _ConcertUpdater_UpdateConcerts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "update.proto",
}
